dbt_demo:
  outputs:
    dev:
      account: xdaomes-te47266
      database: RAW
      password: dbtPassword123
      role: transform
      schema: AIRBNB
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
    prod:
      account: xdaomes-te47266
      database: RAW
      password: dbtPassword123
      role: transform
      schema: AIRBNB
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
